### ISSUE TITLE
As a user, I want to toggle notifications at the times of my choosing, so that I can receive them even when I am not using the app.

### ISSUE THREAD

**Issue by mchan60** [mchan60/JDB-8115#16]
## Story/Task Details
- [ ] Create notification page
- [ ] Create menu to navigate to notifcation page

## Acceptance Scenarios
Scenario 1: A user wants to navigate to the notifications screen from within the app
		Given: The user is within the application
		When: The user clicks Settings -> Notifications
		Then: The user is taken to the notifications menu

Scenario 2: A user wants to turn notification on  from the notifications menu
		Given: The user is in the notifications menu
		When: The user clicks the ‘on’ button and clicks ‘update’
		Then: The app is now allowed to send the user notifications 

Scenario 3: A user wants to toggle diet notifications from the notifications menu
		Given: The user is in the notifications menu and has turned notifications on
		When: The user selects ‘diets’ and clicks ‘update’
		Then: The user will receive reminders about following their diet

Scenario 4: A user wants to toggle recipe notifications from the notifications menu
		Given: The user is in the notifications menu and has turned notifications on
		When: The user selects ‘recipes’ and clicks ‘update’
		Then: The user will receive reminders about following their chosen recipes

Scenario 5: A user wants to control how often they are notified
		Given: The user is in the notifications menu and has turned notifications on
		When: The user selects from an assortment of time intervals  and clicks ‘update’
		Then: The user will now be notified at these time intervals

Scenario 6: A user wants to turn notifications off from the notifications menu
		Given: The user is in the notifications menu
		When: The user clicks the ‘off’ button and clicks ‘update’
		Then: The user will no longer receive notifications

Scenario 7: A user changes their mind about the changes they’ve made to the notifications settings
		Given: The user is in the notifications menu and has made changes
		When: The user does not click ‘update’
		Then: The notifications settings are not altered or updated

## Done Done Criteria
- [ ] Merge dev branch onto feature branch
- [ ] Successfully pass unit tests/debug
- [ ] Submit pull request to be merged onto dev
