### ISSUE TITLE
As a user, I want to have access to a variety of calendar views of my diary so that I can view results over a longer/shorter periods of time.

### ISSUE THREAD

**Issue by awilkins6** [mchan60/JDB-8115#4]
## Story/Task Details
- [ ] Improve UI for daily view
- [ ] Implement weekly view
- [ ] Implement monthly view

## Acceptance Scenarios
Scenario 1: A user wants to access the month view
Given: the user wants to view the diary by the month and is currently not on the 
month view
When: the user goes to the homepage and clicks on the month-view tab 
Then: the user is taken to the month view of the diary

Scenario 2: A user wants to access the week view
Given: the user wants to view the diary by the week and is currently not on the 
week view
When: the user goes to the homepage and clicks on the week-view tab
Then: the user is taken to the week view of the diary

Scenario 3: A user wants to return to day view (the app starts on the day view)
Given: the user wants to view the diary by the day and is currently not on the day 
view
When: the user goes to the homepage and clicks on the day-view tab
Then: the user is taken to the day view of the diary

## Done Done Criteria
- [ ] Merge dev branch onto feature branch
- [ ] Successfully pass unit tests/debug
- [ ] Submit pull request to be merged onto dev
